version: '3.7'

volumes:
  postgres-data:
    name: postgres-data
    driver: local

networks:
  base58_practice:
    name: base58_practice
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_practice

services:

  Base58_practice:
    image: crud/base58_practice
    build:
        context: .
        dockerfile: Dockerfile
    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres

    networks:
      - base58_practice
    ports:
      - "8080:8080"
    depends_on:
      - postgres


  postgres:
    image: postgres:14.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 5s
    networks:
      - base58_practice
    hostname: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@base58.hr
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0

    networks:
      - base58_practice

    depends_on:
      - postgres