version: '3.7'

volumes:
  postgres-data:
    name: postgres-data
    driver: local

networks:
  base58_practice:
    name: base58_practice
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_practice

services:

  Base58_practice:
    image: crud/base58_practice
    build:
        context: .
        dockerfile: Dockerfile
    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres

    networks:
      - base58_practice
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    volumes:
      - ./docker/rabbitmq/import.json:/tmp/import.json
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/tmp/import.json"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
    ports:
      - "15672:15672"
    networks:
      - base58_practice


  postgres:
    image: postgres:14.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 5s
    networks:
      - base58_practice
    hostname: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@base58.hr
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0

    networks:
      - base58_practice

    depends_on:
      - postgres

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:alpine
    command: -H unix:///var/run/docker.sock --admin-password='$$2y$$05$$BNtOCXwleH1JUCz5VuiX5.DxZDLezDoxIlCTn5a0fkIINGWBaQv9.'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:9000 || exit 1" ]
      interval: 1m
      timeout: 30s
    ports:
      - "9000:9000"
